class Types::ProduceTypes < Types::BaseEnum
  value "APPLES_PEARS", "apples and pears"
  value "CITRUS", "oranges, grapefruits, mandarins and limes"
  value "STONE_FRUIT", "nectarines, apricots, peaches and plums"
  value "TROPICAL", "bananas and mangoes"
  value "BERRIES", "strawberries, raspberries, blueberries, kiwifruit and passionfruit"
  value "MELONS", "watermelons, rockmelons and honeydew melons"
  value "TOMATOES_AVOCADOS", "tomatoes and avocados"
  value "LEAFY_GREEN", "lettuce, spinach and silverbeet"
  value "CRUCIFEROUS", "cabbage, cauliflower, Brussels sprouts and broccoli"
  value "MARROW", "pumpkin, cucumber and zucchini"
  value "ROOT", "potato, sweet potato and yam"
  value "PLANT_STEM", "celery and asparagus"
  value "ALLIUM", "onion, garlic and shallot"
  value "SOY", "tofu (bean curd) and soybeans"
  value "LEGUME_FLOURS", "chickpea flour (besan), lentil flour and soy flour"
  value "DRIED_BEANS_PEAS", "haricot beans, red kidney beans, chickpeas and lentils"
  value "FRESH_BEANS_PEAS", "green peas, green beans, butter beans, broad beans and snow peas"
end
